# This is a basic workflow to help you get started with Actions

name: Publish New Release

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      level:
        description: "Level (patch | minor | major)"
        required: true
        default: "patch"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup Git Config
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Restore Packages
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          export NPM_AUTH_TOKEN=$NPM_AUTH_TOKEN
          npm install
          git commit -am "build package lock"

      - name: Create New Version
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          export NPM_AUTH_TOKEN=$NPM_AUTH_TOKEN
          npm version ${{ github.event.inputs.level }}

      - name: Publish Release
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          export NPM_AUTH_TOKEN=$NPM_AUTH_TOKEN
          npm publish
